---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Reload nftables
  ansible.builtin.service:
    name: nftables
    state: reloaded
