---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: Restart journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted

- name: Reload pve-firewall
  ansible.builtin.command:
    cmd: pve-firewall restart
  changed_when: true
