extends: default

ignore: |
  private/
  .git/
  infrastructure/ansible/collections/

rules:
  line-length:
    max: 160
  document-start: disable
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
